ZBUG-143 Admin Console: Last login and Description fields are missing
Zimbra/zm-bulkprovision-store pull request #9
Opened 2022-02-10 19:48 UTC by jholder85638

The search parameters were missing default timestamp and description. They have been added.
The col order will be:
zimbraAccountStatus, zimbraCOSId, description,zimbraLastLogonTimestamp,Human Timestamp (if lastlogin is available)

2022-02-10 19:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Zimbra/zm-bulkprovision-store?pullRequest=9) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Zimbra/zm-bulkprovision-store?pullRequest=9) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Zimbra/zm-bulkprovision-store?pullRequest=9) it.</sub>

2022-02-10 19:49 UTC, jholder85638 commented
Skipping review since this issue was reviewed and approved in https://github.com/ZimbraOS/zm-bulkprovision-store/pull/2

2022-02-11 08:34 UTC, silentsakky commented on zm-bulkprovision-store.iml
> +<?xml version="1.0" encoding="UTF-8"?>
not sure if this file is required

2022-02-14 07:28 UTC, swaatiTelus requested changes
Since we have added LastLogonTimestamp in ACCOUNT_ATTRS and iterated and wrote it into the file at line 107, then, here taking it again will duplicate LastLogonTime data into the file.

2022-02-15 08:10 UTC, jholder85638 commented
Thank you for the feedback! An update has been pushed.
Since the last login timestamp was being printed in the foreach attribute, we now check to see if that's the attribute being concatenated is the timestamp attribute. If it is, we use the date formatted instead.

The null check is still valid as the attribute may be returned with no content.

2022-02-15 11:41 UTC, swaatiTelus approved these changes

2022-02-15 15:18 UTC, silentsakky approved these changes

2022-02-15 15:22 UTC, jholder85638 reviewed
Removed file

2022-02-15 15:22 UTC, jholder85638 commented on zm-bulkprovision-store.iml
> +<?xml version="1.0" encoding="UTF-8"?>
It was spurious and added by intelli. I ave removed it

2022-02-16 06:33 UTC, merged